pragma solidity ^0.4.24;

contract TwoKeyTypes {
	enum CampaignType {CPL, CPA_TOKENS, CPI_SIGN_UP, CPC, CPA_PRODUCT, CPA_SERVICE, CPA_FUNGIBLE, CPA_NON_FUNGIBLE}
	enum CampaignActionType {LEADS, CLICKS, ACQUISITION, SIGN_UP, INSTALL, INFORMATION, VOTE}
}