export const campaignUserActions = {
  visit: 'visit',
  checkManualCutsChain: 'checkManualCutsChain',
  join: 'join',
  joinAndConvert: 'joinAndConvert',
  checkConverterSpent: 'checkConverterSpent',
  cancelConvert: 'cancelConvert',
  executeConversion: 'executeConversion',
  checkPendingConverters: 'checkPendingConverters',
  approveConverter: 'approveConverter',
  rejectConverter: 'rejectConverter',
  checkRestrictedConvert: 'checkRestrictedConvert',
  checkConversionPurchaseInfo: 'checkConversionPurchaseInfo',
  hedgingEth: 'hedgingEth',
  checkCampaignSummary: 'checkCampaignSummary',
  checkModeratorEarnings: 'checkModeratorEarnings',
  withdrawTokens: 'withdrawTokens',
  checkWithdrawableBalance: 'checkWithdrawableBalance',
  contractorWithdraw: 'contractorWithdraw',
  moderatorAndReferrerWithdraw: 'moderatorAndReferrerWithdraw',
  checkTotalEarnings: 'checkTotalEarnings',
  checkStatistic: 'checkStatistic',
  checkConverterMetric: 'checkConverterMetric',
  checkERC20Balance: 'checkERC20Balance',
  createOffline: 'createOffline',
  contractorExecuteConversion: 'contractorExecuteConversion',
  checkReferrersList: 'checkReferrersList',
  checkReferrerReward: 'checkReferrerReward',
  checkTotalReferrerReward: 'checkTotalReferrerReward',
  checkAvailableDonation: 'checkAvailableDonation',
  checkContractorBalanceAndProceeds: 'checkContractorBalanceAndProceeds',
  checkReferrerRewardStats: 'checkReferrerRewardStats',
};

export const maxRefReward = 1666.6666666666667;
