export const campaignUserActions = {
  visit: 'visit',
  join: 'join',
  joinAndConvert: 'joinAndConvert',
  checkConverterSpent: 'checkConverterSpent',
  cancelConvert: 'cancelConvert',
  executeConversion: 'executeConversion',
  checkPendingConverters: 'checkPendingConverters',
  approveConverter: 'approveConverter',
  rejectConverter: 'rejectConverter',
  checkRestrictedConvert: 'checkRestrictedConvert',
  checkConversionPurchaseInfo: 'checkConversionPurchaseInfo',
  hedgingEth: 'hedgingEth',
  checkCampaignSummary: 'checkCampaignSummary',
  checkModeratorEarnings: 'checkModeratorEarnings',
  withdrawTokens: 'withdrawTokens',
  checkWithdrawableBalance: 'checkWithdrawableBalance',
  contractorWithdraw: 'contractorWithdraw',
  moderatorAndReferrerWithdraw: 'moderatorAndReferrerWithdraw',
  checkTotalEarnings: 'checkTotalEarnings',
  checkStatistic: 'checkStatistic',
  checkCampaignMetric: 'checkCampaignMetric',
  checkERC20Balance: 'checkERC20Balance',
  createOffline: 'createOffline',
  contractorExecuteConversion: 'contractorExecuteConversion',
  checkReferrerReward: 'checkReferrerReward',
};
