#!/bin/bash

#parent_pid=$(ps -oppid= -p $PPID)
#push_command=$(ps -ocommand= -p $parent_pid)

MSG="$(cat .git/COMMIT_EDITMSG)"
echo "$(date): '$MSG'" >> build/sol-interface/version.log
echo Commiting: $MSG
# echo TAG: $TAG
# echo SOL TAG: $MTAG

cd build/sol-interface
echo $(pwd)
git add .
# git commit -m "$MSG"

exit 2

# if (("$TAG" != "$MTAG"));
#   then
#     echo ADD TAG $TAG
#   fi
#echo -n $push_command
#echo

# exit 2