/* GENERATED BY TYPECHAIN VER. 0.2.7 */
/* tslint:disable */

import { BigNumber } from "bignumber.js";
import * as TC from "./typechain-runtime";

export class ITwoKeyReg extends TC.TypeChainContract {
  public readonly rawWeb3Contract: any;

  public constructor(web3: any, address: string | BigNumber) {
    const abi = [
      {
        constant: false,
        inputs: [],
        name: "renounceOwnership",
        outputs: [],
        payable: false,
        stateMutability: "nonpayable",
        type: "function"
      },
      {
        constant: true,
        inputs: [],
        name: "owner",
        outputs: [{ name: "", type: "address" }],
        payable: false,
        stateMutability: "view",
        type: "function"
      },
      {
        constant: false,
        inputs: [{ name: "_newOwner", type: "address" }],
        name: "transferOwnership",
        outputs: [],
        payable: false,
        stateMutability: "nonpayable",
        type: "function"
      },
      {
        anonymous: false,
        inputs: [{ indexed: true, name: "previousOwner", type: "address" }],
        name: "OwnershipRenounced",
        type: "event"
      },
      {
        anonymous: false,
        inputs: [
          { indexed: true, name: "previousOwner", type: "address" },
          { indexed: true, name: "newOwner", type: "address" }
        ],
        name: "OwnershipTransferred",
        type: "event"
      },
      {
        constant: false,
        inputs: [{ name: "_twoKeyEventSource", type: "address" }],
        name: "addTwoKeyEventSource",
        outputs: [],
        payable: false,
        stateMutability: "nonpayable",
        type: "function"
      },
      {
        constant: false,
        inputs: [{ name: "_twoKeyEventSource", type: "address" }],
        name: "changeTwoKeyEventSource",
        outputs: [],
        payable: false,
        stateMutability: "nonpayable",
        type: "function"
      },
      {
        constant: false,
        inputs: [
          { name: "_userAddress", type: "address" },
          { name: "_contractAddress", type: "address" }
        ],
        name: "addWhereContractor",
        outputs: [],
        payable: false,
        stateMutability: "nonpayable",
        type: "function"
      },
      {
        constant: false,
        inputs: [
          { name: "_userAddress", type: "address" },
          { name: "_contractAddress", type: "address" }
        ],
        name: "addWhereModerator",
        outputs: [],
        payable: false,
        stateMutability: "nonpayable",
        type: "function"
      },
      {
        constant: false,
        inputs: [
          { name: "_userAddress", type: "address" },
          { name: "_contractAddress", type: "address" }
        ],
        name: "addWhereRefferer",
        outputs: [],
        payable: false,
        stateMutability: "nonpayable",
        type: "function"
      },
      {
        constant: false,
        inputs: [
          { name: "_userAddress", type: "address" },
          { name: "_contractAddress", type: "address" }
        ],
        name: "addWhereConverter",
        outputs: [],
        payable: false,
        stateMutability: "nonpayable",
        type: "function"
      },
      {
        constant: true,
        inputs: [{ name: "_userAddress", type: "address" }],
        name: "getContractsWhereUserIsContractor",
        outputs: [{ name: "", type: "address[]" }],
        payable: false,
        stateMutability: "view",
        type: "function"
      },
      {
        constant: true,
        inputs: [{ name: "_userAddress", type: "address" }],
        name: "getContractsWhereUserIsModerator",
        outputs: [{ name: "", type: "address[]" }],
        payable: false,
        stateMutability: "view",
        type: "function"
      },
      {
        constant: true,
        inputs: [{ name: "_userAddress", type: "address" }],
        name: "getContractsWhereUserIsRefferer",
        outputs: [{ name: "", type: "address[]" }],
        payable: false,
        stateMutability: "view",
        type: "function"
      },
      {
        constant: true,
        inputs: [{ name: "_userAddress", type: "address" }],
        name: "getContractsWhereUserIsConverter",
        outputs: [{ name: "", type: "address[]" }],
        payable: false,
        stateMutability: "view",
        type: "function"
      },
      {
        constant: true,
        inputs: [],
        name: "getTwoKeyEventSourceAddress",
        outputs: [{ name: "", type: "address" }],
        payable: false,
        stateMutability: "view",
        type: "function"
      },
      {
        constant: false,
        inputs: [
          { name: "_name", type: "string" },
          { name: "_sender", type: "address" }
        ],
        name: "addName",
        outputs: [],
        payable: false,
        stateMutability: "nonpayable",
        type: "function"
      },
      {
        constant: false,
        inputs: [{ name: "_name", type: "string" }],
        name: "addNameByUser",
        outputs: [],
        payable: false,
        stateMutability: "nonpayable",
        type: "function"
      },
      {
        constant: true,
        inputs: [{ name: "_name", type: "string" }],
        name: "getName2Owner",
        outputs: [{ name: "", type: "address" }],
        payable: false,
        stateMutability: "view",
        type: "function"
      },
      {
        constant: true,
        inputs: [{ name: "_sender", type: "address" }],
        name: "getOwner2Name",
        outputs: [{ name: "", type: "string" }],
        payable: false,
        stateMutability: "view",
        type: "function"
      }
    ];
    super(web3, address, abi);
  }

  static async createAndValidate(
    web3: any,
    address: string | BigNumber
  ): Promise<ITwoKeyReg> {
    const contract = new ITwoKeyReg(web3, address);
    const code = await TC.promisify(web3.eth.getCode, [address]);

    // in case of missing smartcontract, code can be equal to "0x0" or "0x" depending on exact web3 implementation
    // to cover all these cases we just check against the source code length — there won't be any meaningful EVM program in less then 3 chars
    if (code.length < 4) {
      throw new Error(`Contract at ${address} doesn't exist!`);
    }
    return contract;
  }

  public get owner(): Promise<string> {
    return TC.promisify(this.rawWeb3Contract.owner, []);
  }

  public get getTwoKeyEventSourceAddress(): Promise<string> {
    return TC.promisify(this.rawWeb3Contract.getTwoKeyEventSourceAddress, []);
  }

  public getContractsWhereUserIsContractor(
    _userAddress: BigNumber | string
  ): Promise<string[]> {
    return TC.promisify(
      this.rawWeb3Contract.getContractsWhereUserIsContractor,
      [_userAddress.toString()]
    );
  }

  public getContractsWhereUserIsModerator(
    _userAddress: BigNumber | string
  ): Promise<string[]> {
    return TC.promisify(this.rawWeb3Contract.getContractsWhereUserIsModerator, [
      _userAddress.toString()
    ]);
  }

  public getContractsWhereUserIsRefferer(
    _userAddress: BigNumber | string
  ): Promise<string[]> {
    return TC.promisify(this.rawWeb3Contract.getContractsWhereUserIsRefferer, [
      _userAddress.toString()
    ]);
  }

  public getContractsWhereUserIsConverter(
    _userAddress: BigNumber | string
  ): Promise<string[]> {
    return TC.promisify(this.rawWeb3Contract.getContractsWhereUserIsConverter, [
      _userAddress.toString()
    ]);
  }

  public getName2Owner(_name: string): Promise<string> {
    return TC.promisify(this.rawWeb3Contract.getName2Owner, [_name.toString()]);
  }

  public getOwner2Name(_sender: BigNumber | string): Promise<string> {
    return TC.promisify(this.rawWeb3Contract.getOwner2Name, [
      _sender.toString()
    ]);
  }

  public renounceOwnershipTx(): TC.DeferredTransactionWrapper<TC.ITxParams> {
    return new TC.DeferredTransactionWrapper<TC.ITxParams>(
      this,
      "renounceOwnership",
      []
    );
  }
  public transferOwnershipTx(
    _newOwner: BigNumber | string
  ): TC.DeferredTransactionWrapper<TC.ITxParams> {
    return new TC.DeferredTransactionWrapper<TC.ITxParams>(
      this,
      "transferOwnership",
      [_newOwner.toString()]
    );
  }
  public addTwoKeyEventSourceTx(
    _twoKeyEventSource: BigNumber | string
  ): TC.DeferredTransactionWrapper<TC.ITxParams> {
    return new TC.DeferredTransactionWrapper<TC.ITxParams>(
      this,
      "addTwoKeyEventSource",
      [_twoKeyEventSource.toString()]
    );
  }
  public changeTwoKeyEventSourceTx(
    _twoKeyEventSource: BigNumber | string
  ): TC.DeferredTransactionWrapper<TC.ITxParams> {
    return new TC.DeferredTransactionWrapper<TC.ITxParams>(
      this,
      "changeTwoKeyEventSource",
      [_twoKeyEventSource.toString()]
    );
  }
  public addWhereContractorTx(
    _userAddress: BigNumber | string,
    _contractAddress: BigNumber | string
  ): TC.DeferredTransactionWrapper<TC.ITxParams> {
    return new TC.DeferredTransactionWrapper<TC.ITxParams>(
      this,
      "addWhereContractor",
      [_userAddress.toString(), _contractAddress.toString()]
    );
  }
  public addWhereModeratorTx(
    _userAddress: BigNumber | string,
    _contractAddress: BigNumber | string
  ): TC.DeferredTransactionWrapper<TC.ITxParams> {
    return new TC.DeferredTransactionWrapper<TC.ITxParams>(
      this,
      "addWhereModerator",
      [_userAddress.toString(), _contractAddress.toString()]
    );
  }
  public addWhereReffererTx(
    _userAddress: BigNumber | string,
    _contractAddress: BigNumber | string
  ): TC.DeferredTransactionWrapper<TC.ITxParams> {
    return new TC.DeferredTransactionWrapper<TC.ITxParams>(
      this,
      "addWhereRefferer",
      [_userAddress.toString(), _contractAddress.toString()]
    );
  }
  public addWhereConverterTx(
    _userAddress: BigNumber | string,
    _contractAddress: BigNumber | string
  ): TC.DeferredTransactionWrapper<TC.ITxParams> {
    return new TC.DeferredTransactionWrapper<TC.ITxParams>(
      this,
      "addWhereConverter",
      [_userAddress.toString(), _contractAddress.toString()]
    );
  }
  public addNameTx(
    _name: string,
    _sender: BigNumber | string
  ): TC.DeferredTransactionWrapper<TC.ITxParams> {
    return new TC.DeferredTransactionWrapper<TC.ITxParams>(this, "addName", [
      _name.toString(),
      _sender.toString()
    ]);
  }
  public addNameByUserTx(
    _name: string
  ): TC.DeferredTransactionWrapper<TC.ITxParams> {
    return new TC.DeferredTransactionWrapper<TC.ITxParams>(
      this,
      "addNameByUser",
      [_name.toString()]
    );
  }

  public OwnershipRenouncedEvent(eventFilter: {
    previousOwner?: BigNumber | string | Array<BigNumber | string>;
  }): TC.DeferredEventWrapper<
    { previousOwner: BigNumber | string },
    { previousOwner?: BigNumber | string | Array<BigNumber | string> }
  > {
    return new TC.DeferredEventWrapper<
      { previousOwner: BigNumber | string },
      { previousOwner?: BigNumber | string | Array<BigNumber | string> }
    >(this, "OwnershipRenounced", eventFilter);
  }
  public OwnershipTransferredEvent(eventFilter: {
    previousOwner?: BigNumber | string | Array<BigNumber | string>;
    newOwner?: BigNumber | string | Array<BigNumber | string>;
  }): TC.DeferredEventWrapper<
    { previousOwner: BigNumber | string; newOwner: BigNumber | string },
    {
      previousOwner?: BigNumber | string | Array<BigNumber | string>;
      newOwner?: BigNumber | string | Array<BigNumber | string>;
    }
  > {
    return new TC.DeferredEventWrapper<
      { previousOwner: BigNumber | string; newOwner: BigNumber | string },
      {
        previousOwner?: BigNumber | string | Array<BigNumber | string>;
        newOwner?: BigNumber | string | Array<BigNumber | string>;
      }
    >(this, "OwnershipTransferred", eventFilter);
  }
}
