export default interface CampaignDataInterface {
  amount: number,
  campaignInventory: number,

  maxConverterBonusPercent: number,
  pricePerUnitInETHOrUSD: number,
  maxReferralRewardPercent: number,
  minContributionETHorUSD: number,
  maxContributionETHorUSD: number,
  campaignStartTime: number,
  campaignEndTime: number,
  acquisitionCurrency: string,
  twoKeyEconomy: string,
  isFiatOnly: boolean,
  isFiatConversionAutomaticallyApproved: boolean,
  vestingAmount: string,
  isKYCRequired: boolean,
  incentiveModel: string,
  tokenDistributionDate: number,
  numberOfVestingPortions: number,
  numberOfDaysBetweenPortions: number,
  bonusTokensVestingStartShiftInDaysFromDistributionDate: number,
  maxDistributionDateShiftInDays: number,
}
