/* GENERATED BY TYPECHAIN VER. 0.2.7 */
/* tslint:disable */

import { BigNumber } from "bignumber.js";
import * as TC from "./typechain-runtime";

export class AdminContract extends TC.TypeChainContract {
  public readonly rawWeb3Contract: any;

  public constructor(web3: any, address: string | BigNumber) {
    const abi = [
      {
        constant: false,
        inputs: [{ name: "newAdminContract", type: "address" }],
        name: "replaceOneself",
        outputs: [],
        payable: false,
        stateMutability: "nonpayable",
        type: "function"
      },
      {
        constant: false,
        inputs: [
          { name: "to", type: "address" },
          { name: "tokens", type: "uint256" }
        ],
        name: "transferByAdmins",
        outputs: [],
        payable: false,
        stateMutability: "nonpayable",
        type: "function"
      },
      {
        constant: false,
        inputs: [{ name: "newExchange", type: "address" }],
        name: "upgradeEconomyExchangeByAdmins",
        outputs: [],
        payable: false,
        stateMutability: "nonpayable",
        type: "function"
      },
      {
        constant: false,
        inputs: [
          { name: "to", type: "address" },
          { name: "amount", type: "uint256" }
        ],
        name: "transferEtherByAdmins",
        outputs: [],
        payable: false,
        stateMutability: "nonpayable",
        type: "function"
      }
    ];
    super(web3, address, abi);
  }

  static async createAndValidate(
    web3: any,
    address: string | BigNumber
  ): Promise<AdminContract> {
    const contract = new AdminContract(web3, address);
    const code = await TC.promisify(web3.eth.getCode, [address]);

    // in case of missing smartcontract, code can be equal to "0x0" or "0x" depending on exact web3 implementation
    // to cover all these cases we just check against the source code length — there won't be any meaningful EVM program in less then 3 chars
    if (code.length < 4) {
      throw new Error(`Contract at ${address} doesn't exist!`);
    }
    return contract;
  }

  public replaceOneselfTx(
    newAdminContract: BigNumber | string
  ): TC.DeferredTransactionWrapper<TC.ITxParams> {
    return new TC.DeferredTransactionWrapper<TC.ITxParams>(
      this,
      "replaceOneself",
      [newAdminContract.toString()]
    );
  }
  public transferByAdminsTx(
    to: BigNumber | string,
    tokens: BigNumber | number
  ): TC.DeferredTransactionWrapper<TC.ITxParams> {
    return new TC.DeferredTransactionWrapper<TC.ITxParams>(
      this,
      "transferByAdmins",
      [to.toString(), tokens.toString()]
    );
  }
  public upgradeEconomyExchangeByAdminsTx(
    newExchange: BigNumber | string
  ): TC.DeferredTransactionWrapper<TC.ITxParams> {
    return new TC.DeferredTransactionWrapper<TC.ITxParams>(
      this,
      "upgradeEconomyExchangeByAdmins",
      [newExchange.toString()]
    );
  }
  public transferEtherByAdminsTx(
    to: BigNumber | string,
    amount: BigNumber | number
  ): TC.DeferredTransactionWrapper<TC.ITxParams> {
    return new TC.DeferredTransactionWrapper<TC.ITxParams>(
      this,
      "transferEtherByAdmins",
      [to.toString(), amount.toString()]
    );
  }
}
